Implement new web socket library alternative to socket.io
multiparty/jiff pull request #213
Opened 2020-09-24 15:50 UTC by tsbraun1891

2021-02-26 21:14 UTC, p-flock commented
disconnection bug fixed - still need to figure out why bgw is breaking on this branch only

2021-03-24 16:23 UTC, p-flock requested changes
All looks good after comments are addressed. Add distribution details to extensions documentation md file.

Final thing after these changes is confirming the __internal socket functionality.

2021-03-24 16:23 UTC, p-flock commented on lib/jiff-client.js
> +var jiff_websockets = require('./ext/jiff-client-websockets');
remove

2021-03-24 16:23 UTC, p-flock commented on lib/jiff-client.js
> +  this.jiff_websockets = jiff_websockets;
remove

2021-03-24 16:23 UTC, p-flock commented on tests/suite/config/websocket/constant arithmetic.json
> +      "file": "config/websocket/generation.js",
point to default generation.

2021-03-24 16:23 UTC, p-flock commented on tests/suite/config/websocket/ifelse.json
> +      "file": "config/websocket/generation.js",
point to default generation

2021-03-24 16:23 UTC, p-flock commented on tests/suite/server.js
> +console.log("Extensions: " + extensions);
remove log

2021-03-26 15:49 UTC, p-flock commented
changing the module format for the websocket extensions works in browserify / web-browsers, but breaks in node - a future PR should change all the extensions' module formats and change how we apply extensions to function in node as well.

2021-04-02 19:05 UTC, p-flock approved these changes
All looks good, the  __internal socket seems to work with the extension. I will update the dist/ files and then it is good to go.

2021-04-08 23:06 UTC, KinanBab commented on lib/ext/jiff-client-restful.js
> +    }
not sure I understand why we have this line here

2021-04-08 23:07 UTC, KinanBab commented on lib/ext/jiff-client-websockets.js
> +/**
this looks good to me

2021-04-08 23:17 UTC, KinanBab commented
Overall this is very nice. I am happy that we have websockets now, plus that it was implemented with a relatively "brief"/clean code. I was worried it would end up re-implementing and duplicating many things! Nice work folks.

2021-04-09 02:53 UTC, p-flock commented
> This looks good to me, two minor comments:
> 
>     1. Unsure if the extension will work properly with a server that participates in computation. The reason I worry is because the setup of the socket (with internal_socket etc) might be incompatible with some of the changes. I see some lines of code that was added that made me think that you took this into consideration, but it is worth confirming by testing it (even manually is Ok). I am also OK with this being a separate fix PR.


We manually tested this using the web-mpc demo, led to a couple of changes but everything seems to work as intended now. Reminds me of a previous issue about having a server participate in multiple computations simultaneously, which JIFF by default and this extension don't support - but that is certainly  a separate PR

2021-04-09 15:43 UTC, merged